### ISSUE TITLE
Platform says macOS ×86_64

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [fwcd/m1xxx#23]
I can only assume this is an oversight or for some other reason ? Also thanks for the builds !
![Screenshot 2023-01-10 at 12 40 09](https://user-images.githubusercontent.com/951566/211555316-896f0cdb-33f1-4992-bae3-13873a213309.jpeg)

**Comment by fwcd** [comment]
Yeah, I've wondered about this too. I think the reason is that we cross-compile from an x86_64 GitHub Actions runner, native builds of Mixxx show up as ARM64 in the dialog too. In any case, you should be able to verify that the builds are indeed native in the Activity Monitor:

![Screenshot 2023-02-10 at 15 50 08](https://user-images.githubusercontent.com/30873659/218122133-187a0ef1-1e52-4e22-b250-8f0393a269f6.png)

But this is of course still something that we should fix.

**Comment by fwcd** [comment]
Seems to have been fixed in 7a613825c7c3d37964f2e4c84bd3f941d30c5d08 (which makes sense, given that that's when upstream officially began supporting ARM64).
